### ISSUE TITLE
Rajouter les informations de synchro dans l'édition du produit

### ISSUE THREAD

**Issue by eoxia-amandine** [Eoxia/WPshop#11]
Rajouter les informations de synchro Dolibarr - WPshop dans cette interface :
(même bloc que dans la liste des produits)

![image](https://user-images.githubusercontent.com/18576747/85261349-4d9fb000-b46c-11ea-8be9-7f13a0757842.png)

**Comment by lmag** [comment]
De mémoire c'est un doublon
C'est déjà réalisé
