### ISSUE TITLE
[NEW] :Mise en forme des champs non modifiables

### ISSUE THREAD

**Issue by lmag** [Eoxia/WPshop#19]
![image](https://user-images.githubusercontent.com/3288514/87309787-5b9d9980-c51d-11ea-808f-f6a36834edb8.png)

Mettre les champs au format non lisible de façon intuitive

**Comment by eoxia-amandine** [comment]
- Améliorer le graphisme du "readonly"
- Ajouter une grille pour les champs

**Comment by lmag** [comment]
OK Super
![image](https://user-images.githubusercontent.com/3288514/97014902-36242100-154b-11eb-9cba-5f38889ee53f.png)
