### ISSUE TITLE
[NEW] :Amélioration du bloc avec les boutons d'actions

### ISSUE THREAD

**Issue by lmag** [Eoxia/WPshop#23]
Bloc à mettre à droite pour tous les informations synchronisées
![image](https://user-images.githubusercontent.com/3288514/87315057-4aa45680-c524-11ea-84e0-1edef01dafbf.png)

**Comment by lmag** [comment]
Ne pas mélanger les états et les boutons d'actions

**Comment by eoxia-amandine** [comment]
Proposition d'une amélioration de l'affichage pour le bloc de synchro avec Dolibarr : 
![bloc-synchro-dolibarr](https://user-images.githubusercontent.com/18576747/88307253-0119ef80-cd0c-11ea-828e-1a717fe223cd.png)

**Comment by lmag** [comment]
Le nouveau block est en place
