### ISSUE TITLE
Ouvrir les Proposition Commerciales (PR2006-0001)

### ISSUE THREAD

**Issue by enzo-eoxia** [Eoxia/WPshop#4]
![Issue PropositionCommercialesV2](https://user-images.githubusercontent.com/66355967/84162205-683b5780-aa70-11ea-9029-660665cc82d7.JPG)
En cliquant sur le le lien souligné en rouge, ce message s'affiche :
![Issue PropositionCommerciales](https://user-images.githubusercontent.com/66355967/84162215-6b364800-aa70-11ea-8c7d-1e12a306fb27.JPG)

**Comment by lmag** [comment]
Même erreur sur les commandes, point sur les datas attendues à rajouter

**Comment by lmag** [comment]
ok pr et co
