### ISSUE TITLE
[BUG] Impossible de désactiver une méthode de paiement

### ISSUE THREAD

**Issue by eoxia-amandine** [Eoxia/WPshop#42]
Le toggle "Activer" ne réagis pas au clic.

![image](https://user-images.githubusercontent.com/18576747/95063113-35436080-06fe-11eb-8a78-a92380321a94.png)

-------
**Informations du site** 
`
### wp-core ###

version: 5.5.1
site_language: fr_FR
user_language: fr_FR
timezone: Europe/Paris
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/btpdirect/public_html
wordpress_size: loading...
uploads_path: /home/btpdirect/public_html/wp-content/uploads
uploads_size: loading...
themes_path: /home/btpdirect/public_html/wp-content/themes
themes_size: loading...
plugins_path: /home/btpdirect/public_html/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-active-theme ###

name: BeFlex Child (beflex-child)
version: 3.0.0
author: the Eoxia team
author_website: (undefined)
parent_theme: BeFlex (beflex)
theme_features: core-block-patterns, automatic-feed-links, title-tag, custom-logo, post-thumbnails, align-wide, menus, html5, customize-selective-refresh-widgets, editor-style, widgets
theme_path: /home/btpdirect/public_html/wp-content/themes/beflex-child
auto_update: Désactivé

### wp-parent-theme ###

name: BeFlex (beflex)
version: 3.2.0
author: the Eoxia team
author_website: https://www.eoxia.com
theme_path: /home/btpdirect/public_html/wp-content/themes/beflex
auto_update: Désactivé

### wp-themes-inactive (1) ###

Twenty Twenty: version: 1.5, author: L’équipe WordPress,Mises à jour auto désactivées

### wp-plugins-active (13) ###

ACF Content Analysis for Yoast SEO: version: 3.0, author: Thomas Kräftner, ViktorFroberg, marol87, pekz0r, angrycreative, Team Yoast, Mises à jour auto désactivées
Advanced Custom Fields: Sidebar Selector: version: 3.0.0, author: Daniel Pataki, Mises à jour auto désactivées
Advanced Custom Fields PRO: version: 5.9.1, author: Elliot Condon, Mises à jour auto désactivées
All In One WP Security: version: 4.4.4, author: Tips and Tricks HQ, Peter Petreski, Ruhul, Ivy, Mises à jour auto désactivées
BeFlex Pro: version: 2.2.0, author: Eoxia <dev@eoxia.com>, Mises à jour auto désactivées
Everest Forms: version: 1.7.1, author: WPEverest, Mises à jour auto désactivées
MailPoet 3 (New): version: 3.51.1, author: MailPoet, Mises à jour auto désactivées
MainWP Child: version: 4.1, author: MainWP, Mises à jour auto désactivées
Regenerate Thumbnails: version: 3.1.3, author: Alex Mills (Viper007Bond), Mises à jour auto désactivées
User Switching: version: 1.5.6, author: John Blackbourn & contributors, Mises à jour auto désactivées
Wordfence Security: version: 7.4.11, author: Wordfence, Mises à jour auto désactivées
WPshop 2: version: 2.2.0, author: Eoxia <dev@eoxia.com>, Mises à jour auto désactivées
Yoast SEO: version: 15.0, author: Team Yoast, Mises à jour auto désactivées

### wp-plugins-inactive (1) ###

BeFlex Pro: version: 2.1.0, author: Eoxia <dev@eoxia.com>, Mises à jour auto désactivées

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1690
imagemagick_version: ImageMagick 6.9.10-68 Q16 x86_64 2020-04-01 https://imagemagick.org
file_uploads: File uploads is turned off
post_max_size: 512M
upload_max_filesize: 512M
max_effective_size: 512 Mo
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 188 Go
	imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	imagick::RESOURCETYPE_FILE: 12288
	imagick::RESOURCETYPE_MAP: 188 Go
	imagick::RESOURCETYPE_MEMORY: 94 Go
	imagick::RESOURCETYPE_THREAD: 32
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 9.25

### wp-server ###

server_architecture: Linux 3.10.0-957.27.2.el7.x86_64 x86_64
httpd_software: Apache
php_version: 7.0.33 64bit
php_sapi: litespeed
max_input_variables: 250000
time_limit: 360
memory_limit: 512M
max_input_time: 360
upload_max_filesize: 512M
php_post_max_size: 512M
curl_version: 7.72.0 OpenSSL/1.1.1h
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 10.3.24-MariaDB
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/btpdirect/public_html/wp-content
WP_PLUGIN_DIR: /home/btpdirect/public_html/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

`

**Comment by lmag** [comment]
done
