### ISSUE TITLE
[BUG] - Lecture des catégories ne prends pas en compte la création dans WordPress

### ISSUE THREAD

**Issue by lmag** [Eoxia/WPshop#43]
Les premières catégories existent
Les trois dernières existent uniquement sur dolibarr mais pas de WordPress la requête ne prends pas en compte ce statuts.
![image](https://user-images.githubusercontent.com/3288514/95081035-4483d780-0719-11eb-8c92-9564586c52c8.png)

**Comment by evarisk-theo** [comment]
Fixé dans la 2.3.0

**Comment by lmag** [comment]
Parfait tests ok
