### ISSUE TITLE
[NEW] Liste des utilisateurs tiers (WP) = Liste contact tier (Doli)

### ISSUE THREAD

**Issue by eoxia-amandine** [Eoxia/WPshop#44]
Actuellement, la liste des utilisateurs d'un tier sur WordPress est lié à l'adresse email du tier sur Doli :
 --
**Liste utilisateurs sur WP**
![image](https://user-images.githubusercontent.com/18576747/95997678-4db92680-0e34-11eb-89fe-19f22b377281.png)

---

**Tier sur Doli**
![image](https://user-images.githubusercontent.com/18576747/95997722-5c074280-0e34-11eb-8f06-0e29959ffc4e.png)

---

Ne serait-il pas plus intéressant que la liste d'utilisateurs soit liée à la liste de contact ?
![image](https://user-images.githubusercontent.com/18576747/95997825-7ccf9800-0e34-11eb-9ec9-2c6e713ae52f.png)

**Comment by lmag** [comment]
Pour le moment juste les informations du tiers, il n'y a pas de liaison avec les contacts de dolibarr afin de simplifier

**Comment by lmag** [comment]
Email obligatoire sur le tiers, le "prenom" est un extrafield sur doliwpshop

**Comment by lmag** [comment]
On pourrait juste récupérer la liste des contacts/adresse dans dolibarr sans rien synchroniser
1 seul contact accède à wpshop celui du tiers
Renommer "utilisateurs" "en contact/adresse"

**Comment by lmag** [comment]
Done
