### ISSUE TITLE
[BUG] Afficher dernier devis sur la liste des tiers

### ISSUE THREAD

**Issue by eoxia-amandine** [Eoxia/WPshop#45]
**Description du problème**
La liste des tiers affiche la dernière liste d'envie plutôt que la dernière proposition commerciale

**Captures d'écrans**
![image](https://user-images.githubusercontent.com/18576747/95998455-2adb4200-0e35-11eb-8350-2526d2e1c78a.png)

**Comment by lmag** [comment]
Done
