### ISSUE TITLE
[BUG] Les pages des factures WP ne s'affichent pas

### ISSUE THREAD

**Issue by eoxia-amandine** [Eoxia/WPshop#46]
**Description du problème**
L'ID de la facture n'est pas correcte dans le lien. La page ne s'affiche donc pas

**Captures d'écrans**
![image](https://user-images.githubusercontent.com/18576747/95998816-873e6180-0e35-11eb-991a-6863b9ee9dea.png)

**Comment by lmag** [comment]
Done
