### ISSUE TITLE
[BUG] Les lignes de paiements ne sont pas affichées dans le recap de la commande

### ISSUE THREAD

**Issue by eoxia-amandine** [Eoxia/WPshop#47]
**Description du problème**
Dans le recap de paiement, on voit ce qui a été payé, ce qu'il reste à payer mais on ne voit pas les différentes lignes de paiements ajouté. Sur cet exemple il y a 2 paiements ajoutés via Dolibarr : un par chèque et un par carte.

**Captures d'écrans**
![image](https://user-images.githubusercontent.com/18576747/95999148-e8663500-0e35-11eb-94b9-d19bac55fee1.png)

![image](https://user-images.githubusercontent.com/18576747/95999215-f916ab00-0e35-11eb-92bc-f0b074b67335.png)

**Comment by lmag** [comment]
Rename "déjà réglé"
Le détails des règlements en V2
