### ISSUE TITLE
[BUG] Box "Connexion ERP" ne se ferme pas

### ISSUE THREAD

**Issue by eoxia-amandine** [Eoxia/WPshop#49]
**Description du problème**
Il faut pouvoir fermer la popup "Connexion ERP" qui s'affiche quand il n'y a pas de connexion (dans l'admin).

**Captures d'écrans**
![image](https://user-images.githubusercontent.com/18576747/96473717-45952880-1232-11eb-8354-f7583e2c77a2.png)

**Comment by lmag** [comment]
done
