### ISSUE TITLE
[NEW] :Problème sur l'affichage des taxes

### ISSUE THREAD

**Issue by eoxia-amandine** [Eoxia/WPshop#5]
Après une demande de devis, le récapitulatif n'a pas affiché le montant des taxes :

![image](https://user-images.githubusercontent.com/18576747/84165060-82c30000-aa73-11ea-80d2-97d967dbbb39.png)

**Comment by lmag** [comment]
Supprimer du code les sommes et tous les calculs présenter juste les lignes de produits lorsque l'erp n'est pas connecté
