### ISSUE TITLE
[BUG] affichage dans produits et categories suite version 2.3.1

### ISSUE THREAD

**Issue by jeanmichel83** [Eoxia/WPshop#58]
**Description du problème**
Une description claire et concise.
Suite à la mise à jour vers la 2.3.1 un problème d'affichage sur produits et categories (voir Capture écran)

**Captures d'écrans**
Si possible, ajoutez des captures d'écran pour nous aidez à identifier le problème.
PRODUITS
![image](https://user-images.githubusercontent.com/63457365/99096788-019a0700-25d7-11eb-8876-c2ddb01863bd.png)
CATEGORIES
![image](https://user-images.githubusercontent.com/63457365/99096917-2b532e00-25d7-11eb-9364-b2167154606e.png)

**Configuration de votre WordPress**
Rendez-vous dans l'onglet "Outils" -> "Santé du site" -> "Informations" -> cliquez sur "Copier les informations du site dans le presse-papier". Collez les informations ici.
`
### wp-core ###

version: 5.5.3
site_language: fr_FR
user_language: fr_FR
timezone: Europe/Paris
permalink: /%postname%
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/xnlesjaras/www
wordpress_size: 241,37 Mo (253099665 bytes)
uploads_path: /home/xnlesjaras/www/wp-content/uploads
uploads_size: 81,75 Mo (85720811 bytes)
themes_path: /home/xnlesjaras/www/wp-content/themes
themes_size: 5,99 Mo (6278739 bytes)
plugins_path: /home/xnlesjaras/www/wp-content/plugins
plugins_size: 115,46 Mo (121064481 bytes)
database_size: 22,75 Mo (23855104 bytes)
total_size: 467,32 Mo (490018800 bytes)

### wp-active-theme ###

name: BeFlex Child (beflex-child)
version: 3.0.0
author: the Eoxia team
author_website: (undefined)
parent_theme: BeFlex (beflex)
theme_features: core-block-patterns, widgets-block-editor, editor-style, automatic-feed-links, title-tag, custom-logo, post-thumbnails, align-wide, menus, html5, customize-selective-refresh-widgets, widgets
theme_path: /home/xnlesjaras/www/wp-content/themes/beflex-child
auto_update: Désactivé

### wp-parent-theme ###

name: BeFlex (beflex)
version: 3.1.0
author: the Eoxia team
author_website: https://www.eoxia.com
theme_path: /home/xnlesjaras/www/wp-content/themes/beflex
auto_update: Désactivé

### wp-plugins-active (8) ###

Advanced Custom Fields: Sidebar Selector: version: 3.0.0, author: Daniel Pataki, Mises à jour auto désactivées
Advanced Custom Fields PRO: version: 5.8.4, author: Elliot Condon (latest version: 5.9.3), Mises à jour auto désactivées
BeFlex Pro: version: 2.1.0, author: Eoxia <dev@eoxia.com>, Mises à jour auto désactivées
Gutenberg: version: 9.3.0, author: Gutenberg Team, Mises à jour auto désactivées
Smart Slider 3: version: 3.4.1.13, author: Nextend, Mises à jour auto désactivées
Wordfence Security: version: 7.4.12, author: Wordfence, Mises à jour auto désactivées
WP Maintenance: version: 5.1.0, author: Florent Maillefaud, Mises à jour auto désactivées
WPshop 2: version: 2.3.0, author: Eoxia <dev@eoxia.com>, Mises à jour auto désactivées

### wp-plugins-inactive (8) ###

Akismet Anti-Spam: version: 4.1.7, author: Automattic, Mises à jour auto désactivées
BackWPup: version: 3.8.0, author: Inpsyde GmbH, Mises à jour auto désactivées
OSM: version: 5.5, author: MiKa, Mises à jour auto désactivées
PHP Execution: version: 1.0.0, author: Nicolas Zeh, Mises à jour auto désactivées
Woody ad snippets (PHP snippets | Insert PHP): version: 2.3.10, author: Will Bontrager Software, LLC <will@willmaster.com>, Webcraftic <wordpress.webraftic@gmail.com>, Mises à jour auto désactivées
WordPress Importer: version: 0.7, author: wordpressdotorg, Mises à jour auto désactivées
WordPress Reset: version: 1.4.2, author: Aristeides Stathopoulos, Matt Martz, Mises à jour auto désactivées
WP-Syntax: version: 1.1, author: Steven A. Zahm, Mises à jour auto désactivées

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1673
imagemagick_version: ImageMagick 6.8.9-9 Q16 i586 2019-12-29 http://www.imagemagick.org
file_uploads: File uploads is turned off
post_max_size: 130M
upload_max_filesize: 128M
max_effective_size: 128 Mo
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 
	imagick::RESOURCETYPE_DISK: -1
	imagick::RESOURCETYPE_FILE: 15000
	imagick::RESOURCETYPE_MAP: 
	imagick::RESOURCETYPE_MEMORY: 
	imagick::RESOURCETYPE_THREAD: 8
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 9.26

### wp-server ###

server_architecture: Linux 4.14.154-ovh-vps-grsec-zfs-classid x86_64
httpd_software: Apache
php_version: 7.3.20
php_sapi: fpm-fcgi
max_input_variables: 16000
time_limit: 300
memory_limit: 512M
max_input_time: -1
upload_max_filesize: 128M
php_post_max_size: 130M
curl_version: 7.38.0 OpenSSL/1.0.1t
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.6.50-log
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/xnlesjaras/www/wp-content
WP_PLUGIN_DIR: /home/xnlesjaras/www/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

`

**Comment by lmag** [comment]
Avez vous regarde l'option Debug Mode qui devrait être de base à false dans les Réglages de WPshop

**Comment by lmag** [comment]
@todo valeur par défaut vide

**Comment by jeanmichel83** [comment]
dans réglages de WPshop debug mode est coché
impossible de de décocher
à l'enregistrement il se recoche tout seul

**Comment by lmag** [comment]
On l'a supprimé du code :)
