### ISSUE TITLE
[BUG] impossible passer commande

### ISSUE THREAD

**Issue by jeanmichel83** [Eoxia/WPshop#68]
bonjour, depuis le tunnel de vente impossible de créer commande rien ne se passe après clic sur passer commande ?
le client est créer sur WPshop et dolibarr mais pas la commande ?

**Captures d'écrans**
![image](https://user-images.githubusercontent.com/63457365/100981518-34387f00-3547-11eb-871f-28d68c6848b1.png)

---

**Configuration de votre WordPress**
Rendez-vous dans l'onglet "Outils" -> "Santé du site" -> "Informations" -> cliquez sur "Copier les informations du site dans le presse-papier". Collez les informations ici.
`
### wp-core ###

version: 5.5.3
site_language: fr_FR
user_language: fr_FR
timezone: Europe/Paris
permalink: /%postname%
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 3
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/xnlesjaras/www
wordpress_size: loading...
uploads_path: /home/xnlesjaras/www/wp-content/uploads
uploads_size: loading...
themes_path: /home/xnlesjaras/www/wp-content/themes
themes_size: loading...
plugins_path: /home/xnlesjaras/www/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-dropins (1) ###

advanced-cache.php: true

### wp-active-theme ###

name: BeFlex Child (beflex-child)
version: 3.0.0
author: the Eoxia team
author_website: (undefined)
parent_theme: BeFlex (beflex)
theme_features: core-block-patterns, widgets-block-editor, editor-style, automatic-feed-links, title-tag, custom-logo, post-thumbnails, align-wide, menus, html5, customize-selective-refresh-widgets, widgets
theme_path: /home/xnlesjaras/www/wp-content/themes/beflex-child
auto_update: Désactivé

### wp-parent-theme ###

name: BeFlex (beflex)
version: 3.1.0
author: the Eoxia team
author_website: https://www.eoxia.com
theme_path: /home/xnlesjaras/www/wp-content/themes/beflex
auto_update: Désactivé

### wp-plugins-active (11) ###

Advanced Custom Fields: Sidebar Selector: version: 3.0.0, author: Daniel Pataki, Mises à jour auto désactivées
Advanced Custom Fields PRO: version: 5.8.4, author: Elliot Condon (latest version: 5.9.3), Mises à jour auto désactivées
Advanced Editor Tools (previously TinyMCE Advanced): version: 5.5.1, author: Automattic, Mises à jour auto désactivées
BeFlex Pro: version: 2.2.0, author: Eoxia <dev@eoxia.com>, Mises à jour auto désactivées
Gutenberg: version: 9.5.0, author: Gutenberg Team, Mises à jour auto désactivées
Smart Slider 3: version: 3.4.1.14, author: Nextend, Mises à jour auto désactivées
Ultimate Addons for Gutenberg: version: 1.18.2, author: Brainstorm Force, Mises à jour auto désactivées
Wordfence Security: version: 7.4.12, author: Wordfence, Mises à jour auto désactivées
WP Maintenance: version: 5.1.0, author: Florent Maillefaud, Mises à jour auto désactivées
WPshop 2: version: 2.3.2, author: Eoxia <dev@eoxia.com>, Mises à jour auto désactivées
WP Super Cache: version: 1.7.1, author: Automattic, Mises à jour auto désactivées

### wp-plugins-inactive (7) ###

Akismet Anti-Spam: version: 4.1.7, author: Automattic, Mises à jour auto désactivées
BackWPup: version: 3.8.0, author: Inpsyde GmbH, Mises à jour auto désactivées
OSM: version: 5.5.1, author: MiKa, Mises à jour auto désactivées
PHP Execution: version: 1.0.0, author: Nicolas Zeh, Mises à jour auto désactivées
Woody ad snippets (PHP snippets | Insert PHP): version: 2.3.10, author: Will Bontrager Software, LLC <will@willmaster.com>, Webcraftic <wordpress.webraftic@gmail.com>, Mises à jour auto désactivées
WordPress Importer: version: 0.7, author: wordpressdotorg, Mises à jour auto désactivées
WP-Syntax: version: 1.1, author: Steven A. Zahm, Mises à jour auto désactivées

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1673
imagemagick_version: ImageMagick 6.8.9-9 Q16 i586 2019-12-29 http://www.imagemagick.org
file_uploads: File uploads is turned off
post_max_size: 130M
upload_max_filesize: 128M
max_effective_size: 128 Mo
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 
	imagick::RESOURCETYPE_DISK: -1
	imagick::RESOURCETYPE_FILE: 49151
	imagick::RESOURCETYPE_MAP: 
	imagick::RESOURCETYPE_MEMORY: 
	imagick::RESOURCETYPE_THREAD: 8
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 9.26

### wp-server ###

server_architecture: Linux 4.14.154-ovh-vps-grsec-zfs-classid x86_64
httpd_software: Apache
php_version: 7.3.20
php_sapi: fpm-fcgi
max_input_variables: 16000
time_limit: 300
memory_limit: 512M
max_input_time: -1
upload_max_filesize: 128M
php_post_max_size: 130M
curl_version: 7.38.0 OpenSSL/1.0.1t
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.6.50-log
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/xnlesjaras/www/wp-content
WP_PLUGIN_DIR: /home/xnlesjaras/www/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

`

**Comment by eoxia-amandine** [comment]
Bonjour,
Pouvez-vous remplir le champs "**Adresse postale**" et "**Pays**" puis réessayer de passer commande ?

**Comment by jeanmichel83** [comment]
J'ai fait même resultat ?

Télécharger Outlook pour Android<https://aka.ms/ghei36>
________________________________

**Comment by jeanmichel83** [comment]
Re
Dans reglages de wpshop dans emails
Les boutons configurer renvoie sur articles mais articles est vide ?


Télécharger Outlook pour Android<https://aka.ms/ghei36>
________________________________

**Comment by lmag** [comment]
Avez vous bien activer les commandes dans Dolibarr ? avec les bons droits sur l'API ?

**Comment by jeanmichel83** [comment]
Oui tout est activé

Télécharger Outlook pour Android<https://aka.ms/ghei36>
________________________________

**Comment by jbonlinea** [comment]
Même pb ici

jquery manager n'y change rien

`
### wp-core ###

version: 5.6.1
site_language: fr_FR
user_language: fr_FR
timezone: Europe/Paris
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 1
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 110
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /www
wordpress_size: loading...
uploads_path: /www/wp-content/uploads
uploads_size: loading...
themes_path: /www/wp-content/themes
themes_size: loading...
plugins_path: /www/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-active-theme ###

name: Divi Child (divi-child)
version: 1.0.0
author: Elegant Themes
author_website: https://www.elegantthemes.com
parent_theme: Divi (Divi)
theme_features: core-block-patterns, custom-background, automatic-feed-links, post-thumbnails, menus, title-tag, post-formats, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, customize-selective-refresh-widgets, editor-style, widgets
theme_path: /www/wp-content/themes/divi-child
auto_update: Désactivé

### wp-parent-theme ###

name: Divi (Divi)
version: 4.8.2
author: Elegant Themes
author_website: http://www.elegantthemes.com
theme_path: /www/wp-content/themes/Divi
auto_update: Désactivé

### wp-themes-inactive (3) ###

Twenty Nineteen: version: 1.9, author: L’équipe WordPress, Mises à jour auto désactivées
Twenty Twenty: version: 1.6, author: L’équipe WordPress, Mises à jour auto désactivées
Twenty Twenty-One: version: 1.1, author: L’équipe WordPress, Mises à jour auto désactivées

### wp-plugins-active (28) ###

Block Permissions: version: 1.0.7, author: Mehmet Celik, Mises à jour auto désactivées
Members: version: 3.1.3, author: MemberPress, Mises à jour auto désactivées
Pods - Custom Content Types and Fields: version: 2.7.26, author: Pods Framework Team, Mises à jour auto désactivées
Redirection: version: 5.0.1, author: John Godley, Mises à jour auto désactivées
WPML Media: version: 2.6.2, author: OnTheGoSystems (latest version: 2.6.3), Mises à jour auto désactivées
WPML Multilingual CMS: version: 4.4.8, author: OnTheGoSystems (latest version: 4.4.9), Mises à jour auto désactivées
WPML String Translation: version: 3.1.6, author: OnTheGoSystems (latest version: 3.1.7), Mises à jour auto désactivées
WPML Translation Management: version: 2.10.4, author: OnTheGoSystems (latest version: 2.10.5), Mises à jour auto désactivées
WPshop 2: version: 2.3.3, author: Eoxia <dev@eoxia.com>, Mises à jour auto désactivées

### wp-plugins-inactive (0) ###



### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1802
imagemagick_version: ImageMagick 7.0.10-10 Q16 x86_64 2020-07-09 https://imagemagick.org
file_uploads: File uploads is turned off
post_max_size: 128M
upload_max_filesize: 128M
max_effective_size: 128 Mo
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 63 Go
	imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	imagick::RESOURCETYPE_FILE: 37500
	imagick::RESOURCETYPE_MAP: 63 Go
	imagick::RESOURCETYPE_MEMORY: 31 Go
	imagick::RESOURCETYPE_THREAD: 1
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 9.25

### wp-server ###

server_architecture: Linux 3.10.0-962.3.2.lve1.5.42.el7.x86_64 x86_64
httpd_software: LiteSpeed
php_version: 7.3.25 64bit
php_sapi: litespeed
max_input_variables: 200000
time_limit: 360
memory_limit: 512M
max_input_time: 360
upload_max_filesize: 128M
php_post_max_size: 128M
curl_version: 7.71.0 OpenSSL/1.1.1d
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 10.3.27-MariaDB
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /www/wp-content
WP_PLUGIN_DIR: /www/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### buddypress ###

version: 7.1.0
active_components: Membres
template_pack: BuddyPress Nouveau 7.1.0
! hide-loggedout-adminbar: Non
! bp-disable-account-deletion: Oui
! bp-disable-avatar-uploads: Oui
! bp-disable-cover-image-uploads: Oui

### pods ###

pods-server-software: LiteSpeed
pods-user-agent: Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0
pods-session-save-path: /opt/alt/php73/var/lib/php/session
pods-session-save-path-exists: Oui
pods-session-save-path-writable: Oui
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: Non
pods-opcode-cache-memcached: Non
pods-opcode-cache-opcache: Non
pods-opcode-cache-redis: Non
pods-object-cache-apc: Non
pods-object-cache-apcu: Non
pods-object-cache-memcache: Non
pods-object-cache-memcached: Non
pods-object-cache-redis: Non
pods-memory-current-usage: 135,023M
pods-memory-current-usage-real: 137,008M
pods-network-wide: Non
pods-install-location: /www/wp-content/plugins/pods/
pods-developer: Non
pods-tableless-mode: Non
pods-light-mode: Non
pods-strict: Non
pods-allow-deprecated: Oui
pods-api-cache: Oui
pods-shortcode-allow-evaluate-tags: Non

`

**Comment by lmag** [comment]
Bug avec Stripe réglé

**Comment by jeanmichel83** [comment]
Bonjour, j'ai toujours le même probléme
si j'installe la V2.4.0 j'ai une erreur
![Screen Shot 02-25-21 at 05 22 PM](https://user-images.githubusercontent.com/63457365/109183906-b6bf8c00-778e-11eb-90eb-580671230731.PNG)

**Comment by lmag** [comment]
Avez vous de quoi faire un peu plus de tests car on n'arrive pas a le reproduire

**Comment by lmag** [comment]
A la relecture du message d'erreur il semble que vous ayez plusieurs instance de wpshop sur votre installation WordPress.
Surement 2 dossiers. "already in use"
C'est pour cela que nous ne pouvons pas reproduire
