### ISSUE TITLE
WPShop et Doliwpshop : avancement, mise en production, futur ?

### ISSUE THREAD

**Issue by jbonlinea** [Eoxia/WPshop#71]
Bonjour,

Serait-il possible d'avoir une petite update sur WpShop et DoliWpShop ?   
Je vois que certaines release sont prévues, y a-t-il un calendrier ? 

Aussi, la documentation de wpshop donne des éléments pour en comprendre le fonctionnement, mais il n'y a rien "pour les développeurs". Je souhaiterais savoir si il y a - ou quels sont - les filtres et hooks de wpshop disponibles pour affiner son intégration.

Merci d'avance.

**Comment by lmag** [comment]
La mise a jour en version 2.4 en place : 
La gestion de la prochaine version est noté dans le projet en cours en ce moment c'est le 2.5.0
https://github.com/Eoxia/WPshop/projects/13
