### ISSUE TITLE
[BUG] redirection d'url admin problématique + limitante

### ISSUE THREAD

**Issue by jbonlinea** [Eoxia/WPshop#74]
**Description du problème**

L'url
 https://monsite.net/wp-admin/
 ainsi que d'autres url de l'espace d'administration du site wp 
tel que https://monsite.net/wp-admin/plugins.php,
est/sont redirigée.s vers https://monsite.net/mon-compte/details/

Si je comprends que vous puissiez souhaiter éviter que les client n'accèdent au dashboard afin qu'il restent sur la partie publique / boutique du site, cela contraint très fortement le fonctionnement du site (en pus d'être casse pied lorsque l'on est admin et que l'on ne peut plus desactiver wp-shop autrement qu'avec wp-cli ou en changeant le nom du dossier.

Plus largement, un page mon-compte, peut effectivement être utile.
Mais je trouve ça domage, voir même délétaire d'enprisonner un site dans la logique d'un seul module, aussi bien soit-il.

Un siter par exemple utiliser wp-shop et buddypress, ou autre, et un admin  doit être en mesure de décider du comportement du site, du template des pages personnelles, etc... ou créer des pages personelles sur lesquelles se trouvent différent "block" gutember ou widgets, provenant de différent modules.
Ainsi je verrais bien un block ou un shortcode "wp_shop_mon_compte" ce qui permettrait de le mettre sur une page ou un template au choix.

`
### wp-core ###

version: 5.6.1
site_language: fr_FR
user_language: fr_FR
timezone: Europe/Paris
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 1
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 110
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /www
wordpress_size: loading...
uploads_path: /www/wp-content/uploads
uploads_size: loading...
themes_path: /www/wp-content/themes
themes_size: loading...
plugins_path: /www/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-active-theme ###

name: Divi Child (divi-child)
version: 1.0.0
author: Elegant Themes
author_website: https://www.elegantthemes.com
parent_theme: Divi (Divi)
theme_features: core-block-patterns, custom-background, automatic-feed-links, post-thumbnails, menus, title-tag, post-formats, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, customize-selective-refresh-widgets, editor-style, widgets
theme_path: /www/wp-content/themes/divi-child
auto_update: Désactivé

### wp-parent-theme ###

name: Divi (Divi)
version: 4.8.2
author: Elegant Themes
author_website: http://www.elegantthemes.com
theme_path: /www/wp-content/themes/Divi
auto_update: Désactivé

### wp-themes-inactive (3) ###

Twenty Nineteen: version: 1.9, author: L’équipe WordPress, Mises à jour auto désactivées
Twenty Twenty: version: 1.6, author: L’équipe WordPress, Mises à jour auto désactivées
Twenty Twenty-One: version: 1.1, author: L’équipe WordPress, Mises à jour auto désactivées

### wp-plugins-active (28) ###

Block Permissions: version: 1.0.7, author: Mehmet Celik, Mises à jour auto désactivées
Members: version: 3.1.3, author: MemberPress, Mises à jour auto désactivées
Pods - Custom Content Types and Fields: version: 2.7.26, author: Pods Framework Team, Mises à jour auto désactivées
Redirection: version: 5.0.1, author: John Godley, Mises à jour auto désactivées
WPML Media: version: 2.6.2, author: OnTheGoSystems (latest version: 2.6.3), Mises à jour auto désactivées
WPML Multilingual CMS: version: 4.4.8, author: OnTheGoSystems (latest version: 4.4.9), Mises à jour auto désactivées
WPML String Translation: version: 3.1.6, author: OnTheGoSystems (latest version: 3.1.7), Mises à jour auto désactivées
WPML Translation Management: version: 2.10.4, author: OnTheGoSystems (latest version: 2.10.5), Mises à jour auto désactivées
WPshop 2: version: 2.3.3, author: Eoxia <dev@eoxia.com>, Mises à jour auto désactivées

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1802
imagemagick_version: ImageMagick 7.0.10-10 Q16 x86_64 2020-07-09 https://imagemagick.org
file_uploads: File uploads is turned off
post_max_size: 128M
upload_max_filesize: 128M
max_effective_size: 128 Mo
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 63 Go
	imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	imagick::RESOURCETYPE_FILE: 37500
	imagick::RESOURCETYPE_MAP: 63 Go
	imagick::RESOURCETYPE_MEMORY: 31 Go
	imagick::RESOURCETYPE_THREAD: 1
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 9.25

### wp-server ###

server_architecture: Linux 3.10.0-962.3.2.lve1.5.42.el7.x86_64 x86_64
httpd_software: LiteSpeed
php_version: 7.3.25 64bit
php_sapi: litespeed
max_input_variables: 200000
time_limit: 360
memory_limit: 512M
max_input_time: 360
upload_max_filesize: 128M
php_post_max_size: 128M
curl_version: 7.71.0 OpenSSL/1.1.1d
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 10.3.27-MariaDB
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /www/wp-content
WP_PLUGIN_DIR: /www/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### buddypress ###

version: 7.1.0
active_components: Membres
template_pack: BuddyPress Nouveau 7.1.0
! hide-loggedout-adminbar: Non
! bp-disable-account-deletion: Oui
! bp-disable-avatar-uploads: Oui
! bp-disable-cover-image-uploads: Oui

### pods ###

pods-server-software: LiteSpeed
pods-user-agent: Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0
pods-session-save-path: /opt/alt/php73/var/lib/php/session
pods-session-save-path-exists: Oui
pods-session-save-path-writable: Oui
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: Non
pods-opcode-cache-memcached: Non
pods-opcode-cache-opcache: Non
pods-opcode-cache-redis: Non
pods-object-cache-apc: Non
pods-object-cache-apcu: Non
pods-object-cache-memcache: Non
pods-object-cache-memcached: Non
pods-object-cache-redis: Non
pods-memory-current-usage: 135,023M
pods-memory-current-usage-real: 137,008M
pods-network-wide: Non
pods-install-location: /www/wp-content/plugins/pods/
pods-developer: Non
pods-tableless-mode: Non
pods-light-mode: Non
pods-strict: Non
pods-allow-deprecated: Oui
pods-api-cache: Oui
pods-shortcode-allow-evaluate-tags: Non

`

**Comment by lmag** [comment]
Effectivement, nous n'avons pas fait dans la dentelle ...

**Comment by lmag** [comment]
Pour le moment au vu du travail sur cette demande... On ne pourra pas l'implémenter sans demandes de client c'est un peu trop de travail pour le moment ;(

**Comment by jbonlinea** [comment]
Bonjour, 

Je vois que l'issue est close et supprimée de la roadmap.
Supprimée de la roadmap, je comprends si pas dans vos priorité, mais close sugère que c'est réglé, or j'en doute ;  

ps : je n'utilise pas wpshop et j'ai arrété de faire des test en raisons de quelques gros bugs et problème d'ergonomie notament celle-ci ;
