### ISSUE TITLE
[BUG] Génération des permaliens des produits

### ISSUE THREAD

**Issue by eoxia-amandine** [Eoxia/WPshop#78]
Les permaliens des produits prennent le nom de l'image de la galerie produit + extension du fichier.
**Le permalien devrait reprendre le nom du produit ?**

![image](https://user-images.githubusercontent.com/18576747/108344470-75067280-71dd-11eb-98ac-7ecbb4da634d.png)
![image](https://user-images.githubusercontent.com/18576747/108344549-8ea7ba00-71dd-11eb-82e6-e8d4a2943403.png)

**Comment by lmag** [comment]
Il n'y a plus d'image et de synchronisation tous est en direct sur dolibarr :)
