### ISSUE TITLE
Contenu standard des Emails

### ISSUE THREAD

**Issue by lmag** [Eoxia/WPshop#8]
Réaliser le contenu standard des Emails

**Comment by lmag** [comment]
* Nouveau compte
* Commande en cours
* Nouvelle commande payée
* Votre facture

**Comment by cedric-eoxia** [comment]
**Nouveau compte**
Bienvenue 
Cet email vous confirme que votre compte a bien été créé. Merci pour votre confiance et à bientôt sur notre boutique.

**Commande en cours**
Bonjour
Nous venons d'enregistrer votre commande, merci de nous faire parvenir votre règlement.
Nous vous remercions pour votre confiance et à bientôt sur notre boutique.

**Nouvelle commande payée**
Bonjour
Cet email confirme que votre paiement concernant votre commande récente viens d'être validé. 
A très bientôt sur notre boutique.

**Votre facture**
Bonjour
Vous pouvez accéder à vos factures en vous connectant à votre compte.

**Comment by lmag** [comment]
@cedric-eoxia pense à notifier nicolas 👍

**Comment by lmag** [comment]
OK à mettre dans les pages par défaut

**Comment by lmag** [comment]
Le projet est crée il permettra de réaliser une installation standard des Emails 
https://github.com/Eoxia/dolimail
