### ISSUE TITLE
Modification produit mal prise en compte

### ISSUE THREAD

**Issue by eoxia-amandine** [Eoxia/WPshop#9]
Lorsque l'on modifie un produit sur Dolibarr, il doit se mettre à jour sur WordPress.
Il faut vérifier que le script fonctionne entièrement car j'ai rencontré un problème dans le cas suivant : 

J'ai modifié le titre sur Dolibarr, le produit WP s'est mis à jour.
J'ai modifié uniquement la description sur Dolibarr, **le produit ne s'est pas mis à jour.**

**Comment by lmag** [comment]
Le produit est t'il toujours synchro au niveau du listing ? "rond vert" ?

**Comment by lmag** [comment]
Le SHA doit être différent, a controler

**Comment by lmag** [comment]
Il manque la description dans le SHA : 
https://github.com/Eoxia/wpshop/blob/a62f67e5860f1f52e2f584f5150b47df27a49aa9/modules/doli-products/class/class-doli-products.php#L77

**Comment by lmag** [comment]
Document mis à jour :
https://github.com/Eoxia/WPShop-2/blob/master/modules/dolibarr/doli-products/class/class-doli-products.php#L64
